### ISSUE TITLE
Bad response Service Unavailable 503

### ISSUE THREAD

**Issue by Chetan-unbounce** [gemfury/gemfury#78]
Getting "bad response Service Unavailable 503" while installing private packages hosted on Gemfury.

**Comment by wpniederer** [comment]
I'm seeing this issue on a private repo well, it's blocking deployments. Their status page isn't updated, can we get some sort of response on this problem?

https://status.fury.co/

**Comment by 8bitDesigner** [comment]
Hate to be that guy, but I'm gonna 👍  that. I've opened a support ticket with GemFury and I'll let you know if I hear back.

**Comment by wpniederer** [comment]
> Hate to be that guy, but I'm gonna 👍 that. I've opened a support ticket with GemFury and I'll let you know if I hear back.

I also opened a support ticket about 2 hours ago. No response yet.

**Comment by scifisamurai** [comment]
Same issue here; 503'ing for me and some coworkers.

**Comment by ljhenne** [comment]
Piling on here. Same issue for us as well. Blocking all deployments.

**Comment by mohitDeshpande** [comment]
Getting a 503 for the past 3 hours on a private repo

**Comment by Lygre** [comment]
Same problem over here

**Comment by Hector-Ariceaga** [comment]
Ditto

**Comment by AlexanderNZ** [comment]
I've sent them an email to hello@gemfury and also tagged them on twitter. No response from either of those.
If it's bad enough to prevent a response from both social and formal support means, and bad enough to knock out the management portal as well as API, and in a way that prevents the status page from being updated, that's a pretty serious problem :thinking:

**Comment by tdlm** [comment]
Same issue here.

**Comment by prasvin** [comment]
Same here. Unable to fetch the gems. https://gem.fury.io says bad response Service Unavailable 503
I was expecting the status page https://status.fury.co/ to list some incident. Apparently, it's all green there.

**Comment by samgranieri** [comment]
Same problem here...

**Comment by mbelang** [comment]
Worse package manager ever... We will ditch it tomorrow.

**Comment by baburdick** [comment]
Sanitized backtrace:

`Gem::RemoteFetcher::FetchError: bad response Service Unavailable 503`

```
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:245:in `fetch_http'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:263:in `fetch_path'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/rubygems_integration.rb:751:in `fetch_specs'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/rubygems_integration.rb:761:in `fetch_all_remote_specs'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/fetcher/index.rb:10:in `specs'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/fetcher.rb:129:in `block in specs'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/fetcher.rb:128:in `each'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/fetcher.rb:128:in `specs'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/fetcher.rb:113:in `block in specs_with_retry'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/retry.rb:40:in `run'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/retry.rb:30:in `attempt'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/fetcher.rb:112:in `specs_with_retry'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/source/rubygems.rb:411:in `block in fetch_names'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/source/rubygems.rb:404:in `each'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/source/rubygems.rb:404:in `fetch_names'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/source/rubygems.rb:390:in `block in remote_specs'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/index.rb:11:in `build'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/source/rubygems.rb:386:in `remote_specs'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/source/rubygems.rb:89:in `specs'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:273:in `block (2 levels) in index'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:271:in `each'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:271:in `block in index'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/index.rb:11:in `build'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:268:in `index'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:258:in `resolve'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:170:in `specs'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:158:in `resolve_remotely!'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:310:in `resolve_if_needed'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:84:in `block in run'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:12:in `block in lock'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:9:in `open'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:9:in `lock'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:73:in `run'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:25:in `install'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli/update.rb:61:in `run'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:280:in `update'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:18:in `start'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
~/.rvm/rubies/ruby-2.6.6/bin/bundle:23:in `load'
~/.rvm/rubies/ruby-2.6.6/bin/bundle:23:in `<main>'
~/.rvm/gems/ruby-2.6.6@my_service/bin/ruby_executable_hooks:24:in `eval'
~/.rvm/gems/ruby-2.6.6@my_service/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by baburdick** [comment]
Status page is finally acknowledging the issue:
<img width="1310" alt="GemFury-status-page" src="https://user-images.githubusercontent.com/24587/115492131-cc997c80-a226-11eb-8ada-08be156787de.png">

**Comment by baburdick** [comment]
FYI: I was finally just now able to `bundle update`.

**Comment by baburdick** [comment]
This appears to be resolved. I received a message from tech support saying they had "an elevated-error incident that [they] have since mitigated". And their status page now says "A number of repo instances have crashed. Restarted crashed instances, and scaled up. This should have been handled automatically - looking into why this did not happen."

**Comment by wpniederer** [comment]
> This appears to be resolved. I received a message from tech support saying they had "an elevated-error incident that [they] have since mitigated". And their status page now says "A number of repo instances have crashed. Restarted crashed instances, and scaled up. This should have been handled automatically - looking into why this did not happen."

Got the same email from support on my end.

**Comment by Chetan-unbounce** [comment]
Thanks, at least the issue is resolved took some time and lots of peeps complaining but as they say 'all is well that ends well'. Closing the issue for now
